model: "anthropic:claude-opus-4-5-20251101"
model_name: ${.model}
cost_map:
  output_tokens: 75 * 10**-6
  input_tokens: 15 * 10**-6
  cache_read_input_tokens: 1.5 * 10**-6
  cache_creation_input_tokens: 18.75 * 10**-6
  reasoning_tokens: 0 # to keep track of reasoning tokens
kwargs:
  max_tokens: 16384
  top_k: 40
  streaming: false
  temperature: 0.0
