model: "anthropic:claude-sonnet-4-5-20250929"
model_name: ${.model}
cost_map:
  output_tokens: 15 * 10**-6
  input_tokens: 3 * 10**-6
kwargs:
  temperature: 0.0
  max_tokens: 16384
  top_p: 0.8
  top_k: 40
  streaming: false
