model: "openai:gpt-5.2-2025-12-11"
model_name: ${.model}
kwargs:
  temperature: 0.5
  max_tokens: 16384
  streaming: false
  use_responses_api: true
  reasoning:
    effort: low
  text:
    verbosity: medium
